using ProjectManagement.Core.Enums;

namespace ProjectManagement.Core.Entities;

/// <summary>
/// Represents a developer story derived from a WorkItem
/// </summary>
public class DeveloperStory : Entity
{
    /// <summary>
    /// The parent work item this story belongs to
    /// </summary>
    public int WorkItemId { get; set; }

    /// <summary>
    /// Navigation property to the parent work item
    /// </summary>
    public WorkItem? WorkItem { get; set; }

    /// <summary>
    /// The type of developer story
    /// </summary>
    public DeveloperStoryType StoryType { get; set; }

    /// <summary>
    /// Title of the developer story
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Detailed description
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Implementation instructions (typically generated by Claude)
    /// </summary>
    public string Instructions { get; set; } = string.Empty;

    /// <summary>
    /// Priority level (inherited from parent WorkItem)
    /// </summary>
    public int Priority { get; set; } = 5;

    /// <summary>
    /// Current status of the developer story
    /// </summary>
    public DeveloperStoryStatus Status { get; set; } = DeveloperStoryStatus.Pending;

    /// <summary>
    /// Git branch name (if created)
    /// </summary>
    public string? GitBranch { get; set; }

    /// <summary>
    /// Git worktree path (if created)
    /// </summary>
    public string? GitWorktree { get; set; }

    /// <summary>
    /// Timestamp when implementation started
    /// </summary>
    public DateTime? StartedAt { get; set; }

    /// <summary>
    /// Timestamp when implementation completed
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Error message if status is Error
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Additional metadata as JSON
    /// </summary>
    public string? Metadata { get; set; }

    /// <summary>
    /// Navigation property to dependencies this story requires
    /// </summary>
    public ICollection<DeveloperStoryDependency> Dependencies { get; set; } = new List<DeveloperStoryDependency>();

    /// <summary>
    /// Navigation property to stories that depend on this one
    /// </summary>
    public ICollection<DeveloperStoryDependency> DependentStories { get; set; } = new List<DeveloperStoryDependency>();

    /// <summary>
    /// Navigation property to execution logs
    /// </summary>
    public ICollection<ExecutionLog> ExecutionLogs { get; set; } = new List<ExecutionLog>();

    /// <summary>
    /// Gets the default worktree name for this story
    /// </summary>
    public string WorktreeName => $"ds-{Id}";

    /// <summary>
    /// Updates the status and sets appropriate timestamps
    /// </summary>
    public void UpdateStatus(DeveloperStoryStatus newStatus, string? errorMessage = null)
    {
        Status = newStatus;
        ErrorMessage = errorMessage;

        if (newStatus == DeveloperStoryStatus.InProgress && !StartedAt.HasValue)
        {
            StartedAt = DateTime.UtcNow;
        }

        if (newStatus == DeveloperStoryStatus.Completed && !CompletedAt.HasValue)
        {
            CompletedAt = DateTime.UtcNow;
        }

        if (newStatus == DeveloperStoryStatus.Pending)
        {
            // Reset timestamps when going back to pending
            StartedAt = null;
            CompletedAt = null;
        }
    }

    /// <summary>
    /// Checks if the story can transition to the specified status
    /// </summary>
    public bool CanTransitionTo(DeveloperStoryStatus newStatus)
    {
        return (Status, newStatus) switch
        {
            (DeveloperStoryStatus.Pending, DeveloperStoryStatus.Ready) => true,
            (DeveloperStoryStatus.Pending, DeveloperStoryStatus.Blocked) => true,
            (DeveloperStoryStatus.Pending, DeveloperStoryStatus.Error) => true,
            (DeveloperStoryStatus.Ready, DeveloperStoryStatus.InProgress) => true,
            (DeveloperStoryStatus.Ready, DeveloperStoryStatus.Blocked) => true,
            (DeveloperStoryStatus.Ready, DeveloperStoryStatus.Error) => true,
            (DeveloperStoryStatus.InProgress, DeveloperStoryStatus.Completed) => true,
            (DeveloperStoryStatus.InProgress, DeveloperStoryStatus.Error) => true,
            (DeveloperStoryStatus.InProgress, DeveloperStoryStatus.Blocked) => true,
            (DeveloperStoryStatus.Blocked, DeveloperStoryStatus.Ready) => true,
            (DeveloperStoryStatus.Blocked, DeveloperStoryStatus.Error) => true,
            (DeveloperStoryStatus.Error, DeveloperStoryStatus.Pending) => true,
            (DeveloperStoryStatus.Error, DeveloperStoryStatus.Ready) => true,
            _ => false
        };
    }

    /// <summary>
    /// Checks if all dependencies are completed
    /// </summary>
    public bool AreDependenciesCompleted()
    {
        return Dependencies.All(d => d.RequiredStory?.Status == DeveloperStoryStatus.Completed);
    }
}
